/**
 * Knetik.io Data Collector REST API
 * <p>Use this API to send application data to Knetik.io including user/device information and transactional events.</p> <p>   Please consult the <a href=\"/doc\">official user documentation</a> to find out how to send data, and how this data is used. <p></p> <h2>Notes</h2> <br> New more ReSTful implementation of the telemetry data collection service. Legacy clients can still use the old API format, but we strongly recommend switching over to this new format. Navigate to the legacy documentation using the dropdown at the top of this page. <p></p> <h2>User IDs and Device IDs</h2> <br> Knetik.io can uniquely associate state, events and transactions to users and/or devices for your application. In order to accomplish this, each API call takes userId and deviceId as parameters in the request object. At least one of these must be provided in the request object, except as explicitly noted. <br> <p></p> <h2>Timestamps</h2> <br> All timestamp parameters must be epoch timestamps in milliseconds. <br> <p></p> <h2>Required Request Headers</h2> <br> The following HTTP header values must be provided for each API call: <ul>   <li>     <b>Content-Type: application/json</b>   </li> </ul> <p></p> <h2>Required Query Parameters</h2> <br> All API calls also require the following query parameters to be present on the URL: <ul>   <li>     <b>customer_id:</b> your unique customer ID   </li> </ul> <p></p> <h2>API Responses</h2> <br> If successful, API calls will simply return an HTTP response code of ACCEPTED (202) with no other data. If errors occur, a JSON payload will be returned containing detailed error information and an appropriate HTTP error status code will be provided (as documented in each of the API methods). <br> <p></p>
 *
 * OpenAPI spec version: 2.0
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "BatchRequestResult.h"

namespace io {
namespace knetik {
namespace client {
namespace model {

BatchRequestResult::BatchRequestResult()
{
    m_Code = 0;
    m_CodeIsSet = false;
    m_ErrorsIsSet = false;
    m_RequestIsSet = false;
}

BatchRequestResult::~BatchRequestResult()
{
}

void BatchRequestResult::validate()
{
    // TODO: implement validation
}

web::json::value BatchRequestResult::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_CodeIsSet)
    {
        val[U("code")] = ModelBase::toJson(m_Code);
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Errors )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[U("errors")] = web::json::value::array(jsonArray);
        }
    }
    if(m_RequestIsSet)
    {
        val[U("request")] = ModelBase::toJson(m_Request);
    }

    return val;
}

void BatchRequestResult::fromJson(web::json::value& val)
{
    if(val.has_field(U("code")))
    {
        setCode(ModelBase::int32_tFromJson(val[U("code")]));
    }
    {
        m_Errors.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(U("errors")))
        {
        for( auto& item : val[U("errors")].as_array() )
        {
            m_Errors.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
    if(val.has_field(U("request")))
    {
        if(!val[U("request")].is_null())
        {
            std::shared_ptr<DataCollectorBaseRequest> newItem(new DataCollectorBaseRequest());
            newItem->fromJson(val[U("request")]);
            setRequest( newItem );
        }
    }
}

void BatchRequestResult::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_CodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("code"), m_Code));
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Errors )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + U("errors"), web::json::value::array(jsonArray), U("application/json")));
        }
    }
    if(m_RequestIsSet)
    {
        if (m_Request.get())
        {
            m_Request->toMultipart(multipart, U("request."));
        }
        
    }
}

void BatchRequestResult::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("code")))
    {
        setCode(ModelBase::int32_tFromHttpContent(multipart->getContent(U("code"))));
    }
    {
        m_Errors.clear();
        if(multipart->hasContent(U("errors")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("errors"))));
        for( auto& item : jsonArray.as_array() )
        {
            m_Errors.push_back(ModelBase::stringFromJson(item));
        }
        }
    }
    if(multipart->hasContent(U("request")))
    {
        if(multipart->hasContent(U("request")))
        {
            std::shared_ptr<DataCollectorBaseRequest> newItem(new DataCollectorBaseRequest());
            newItem->fromMultiPart(multipart, U("request."));
            setRequest( newItem );
        }
    }
}

int32_t BatchRequestResult::getCode() const
{
    return m_Code;
}


void BatchRequestResult::setCode(int32_t value)
{
    m_Code = value;
    m_CodeIsSet = true;
}
bool BatchRequestResult::codeIsSet() const
{
    return m_CodeIsSet;
}

void BatchRequestResult::unsetCode()
{
    m_CodeIsSet = false;
}

std::vector<utility::string_t>& BatchRequestResult::getErrors()
{
    return m_Errors;
}

void BatchRequestResult::setErrors(std::vector<utility::string_t> value)
{
    m_Errors = value;
    m_ErrorsIsSet = true;
}
bool BatchRequestResult::errorsIsSet() const
{
    return m_ErrorsIsSet;
}

void BatchRequestResult::unsetErrors()
{
    m_ErrorsIsSet = false;
}

std::shared_ptr<DataCollectorBaseRequest> BatchRequestResult::getRequest() const
{
    return m_Request;
}


void BatchRequestResult::setRequest(std::shared_ptr<DataCollectorBaseRequest> value)
{
    m_Request = value;
    m_RequestIsSet = true;
}
bool BatchRequestResult::requestIsSet() const
{
    return m_RequestIsSet;
}

void BatchRequestResult::unsetRequest()
{
    m_RequestIsSet = false;
}

}
}
}
}

