/**
 * Knetik.io Data Collector REST API
 * <p>Use this API to send application data to Knetik.io including user/device information and transactional events.</p> <p>   Please consult the <a href=\"/doc\">official user documentation</a> to find out how to send data, and how this data is used. <p></p> <h2>Notes</h2> <br> New more ReSTful implementation of the telemetry data collection service. Legacy clients can still use the old API format, but we strongly recommend switching over to this new format. Navigate to the legacy documentation using the dropdown at the top of this page. <p></p> <h2>User IDs and Device IDs</h2> <br> Knetik.io can uniquely associate state, events and transactions to users and/or devices for your application. In order to accomplish this, each API call takes userId and deviceId as parameters in the request object. At least one of these must be provided in the request object, except as explicitly noted. <br> <p></p> <h2>Timestamps</h2> <br> All timestamp parameters must be epoch timestamps in milliseconds. <br> <p></p> <h2>Required Request Headers</h2> <br> The following HTTP header values must be provided for each API call: <ul>   <li>     <b>Content-Type: application/json</b>   </li> </ul> <p></p> <h2>Required Query Parameters</h2> <br> All API calls also require the following query parameters to be present on the URL: <ul>   <li>     <b>customer_id:</b> your unique customer ID   </li> </ul> <p></p> <h2>API Responses</h2> <br> If successful, API calls will simply return an HTTP response code of ACCEPTED (202) with no other data. If errors occur, a JSON payload will be returned containing detailed error information and an appropriate HTTP error status code will be provided (as documented in each of the API methods). <br> <p></p>
 *
 * OpenAPI spec version: 2.0
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * BatchRequestResult.h
 *
 * 
 */

#ifndef BatchRequestResult_H_
#define BatchRequestResult_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "DataCollectorBaseRequest.h"
#include <vector>

namespace io {
namespace knetik {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  BatchRequestResult
    : public ModelBase
{
public:
    BatchRequestResult();
    virtual ~BatchRequestResult();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BatchRequestResult members

    /// <summary>
    /// HTTP response code for the processed request
    /// </summary>
    int32_t getCode() const;
    bool codeIsSet() const;
    void unsetCode();
    void setCode(int32_t value);
    /// <summary>
    /// Error messages if the request could not be processed
    /// </summary>
    std::vector<utility::string_t>& getErrors();
    bool errorsIsSet() const;
    void unsetErrors();
    void setErrors(std::vector<utility::string_t> value);
    /// <summary>
    /// The request. Will be null if request was successfully processed
    /// </summary>
    std::shared_ptr<DataCollectorBaseRequest> getRequest() const;
    bool requestIsSet() const;
    void unsetRequest();
    void setRequest(std::shared_ptr<DataCollectorBaseRequest> value);

protected:
    int32_t m_Code;
    bool m_CodeIsSet;
    std::vector<utility::string_t> m_Errors;
    bool m_ErrorsIsSet;
    std::shared_ptr<DataCollectorBaseRequest> m_Request;
    bool m_RequestIsSet;
};

}
}
}
}

#endif /* BatchRequestResult_H_ */
