/**
 * Knetik.io Data Collector REST API
 * <p>Use this API to send application data to Knetik.io including user/device information and transactional events.</p> <p>   Please consult the <a href=\"/doc\">official user documentation</a> to find out how to send data, and how this data is used. <p></p> <h2>Notes</h2> <br> New more ReSTful implementation of the telemetry data collection service. Legacy clients can still use the old API format, but we strongly recommend switching over to this new format. Navigate to the legacy documentation using the dropdown at the top of this page. <p></p> <h2>User IDs and Device IDs</h2> <br> Knetik.io can uniquely associate state, events and transactions to users and/or devices for your application. In order to accomplish this, each API call takes userId and deviceId as parameters in the request object. At least one of these must be provided in the request object, except as explicitly noted. <br> <p></p> <h2>Timestamps</h2> <br> All timestamp parameters must be epoch timestamps in milliseconds. <br> <p></p> <h2>Required Request Headers</h2> <br> The following HTTP header values must be provided for each API call: <ul>   <li>     <b>Content-Type: application/json</b>   </li> </ul> <p></p> <h2>Required Query Parameters</h2> <br> All API calls also require the following query parameters to be present on the URL: <ul>   <li>     <b>customer_id:</b> your unique customer ID   </li> </ul> <p></p> <h2>API Responses</h2> <br> If successful, API calls will simply return an HTTP response code of ACCEPTED (202) with no other data. If errors occur, a JSON payload will be returned containing detailed error information and an appropriate HTTP error status code will be provided (as documented in each of the API methods). <br> <p></p>
 *
 * OpenAPI spec version: 2.0
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * DataCollectorEndTransactionRequest.h
 *
 * 
 */

#ifndef DataCollectorEndTransactionRequest_H_
#define DataCollectorEndTransactionRequest_H_


#include <cpprest/details/basic_types.h>
#include "DataCollectorBaseRequest.h"
#include "Object.h"

namespace io {
namespace knetik {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  DataCollectorEndTransactionRequest
    : public DataCollectorBaseRequest
{
public:
    DataCollectorEndTransactionRequest();
    virtual ~DataCollectorEndTransactionRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DataCollectorEndTransactionRequest members

    /// <summary>
    /// The outcome of the transaction. Can be anything from a code to a word to a boolean depending on your neeeds. Ex: success, 200, invalid, insufficient_funds, etc
    /// </summary>
    utility::string_t getResult() const;
        void setResult(utility::string_t value);
    /// <summary>
    /// Unique transaction ID
    /// </summary>
    utility::string_t getTransactionId() const;
    bool transactionIdIsSet() const;
    void unsetTransaction_id();
    void setTransactionId(utility::string_t value);
    /// <summary>
    /// The name/type of the transaction
    /// </summary>
    utility::string_t getCategory() const;
        void setCategory(utility::string_t value);

protected:
    utility::string_t m_Result;
        utility::string_t m_Transaction_id;
    bool m_Transaction_idIsSet;
    utility::string_t m_Category;
    };

}
}
}
}

#endif /* DataCollectorEndTransactionRequest_H_ */
