/**
 * Knetik.io Data Collector REST API
 * <p>Use this API to send application data to Knetik.io including user/device information and transactional events.</p> <p>   Please consult the <a href=\"/doc\">official user documentation</a> to find out how to send data, and how this data is used. <p></p> <h2>Notes</h2> <br> New more ReSTful implementation of the telemetry data collection service. Legacy clients can still use the old API format, but we strongly recommend switching over to this new format. Navigate to the legacy documentation using the dropdown at the top of this page. <p></p> <h2>User IDs and Device IDs</h2> <br> Knetik.io can uniquely associate state, events and transactions to users and/or devices for your application. In order to accomplish this, each API call takes userId and deviceId as parameters in the request object. At least one of these must be provided in the request object, except as explicitly noted. <br> <p></p> <h2>Timestamps</h2> <br> All timestamp parameters must be epoch timestamps in milliseconds. <br> <p></p> <h2>Required Request Headers</h2> <br> The following HTTP header values must be provided for each API call: <ul>   <li>     <b>Content-Type: application/json</b>   </li> </ul> <p></p> <h2>Required Query Parameters</h2> <br> All API calls also require the following query parameters to be present on the URL: <ul>   <li>     <b>customer_id:</b> your unique customer ID   </li> </ul> <p></p> <h2>API Responses</h2> <br> If successful, API calls will simply return an HTTP response code of ACCEPTED (202) with no other data. If errors occur, a JSON payload will be returned containing detailed error information and an appropriate HTTP error status code will be provided (as documented in each of the API methods). <br> <p></p>
 *
 * OpenAPI spec version: 2.0
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "DataCollectorNewUserRequest.h"

namespace io {
namespace knetik {
namespace client {
namespace model {

DataCollectorNewUserRequest::DataCollectorNewUserRequest()
{
    m_DeviceId = U("");
    m_DeviceIdIsSet = false;
    m_EventPropertiesIsSet = false;
    m_EventTimestamp = 0;
    m_RequestType = U("");
    m_SendTimestamp = 0;
    m_UserId = U("");
    
}

DataCollectorNewUserRequest::~DataCollectorNewUserRequest()
{
}

void DataCollectorNewUserRequest::validate()
{
    // TODO: implement validation
}

web::json::value DataCollectorNewUserRequest::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_DeviceIdIsSet)
    {
        val[U("deviceId")] = ModelBase::toJson(m_DeviceId);
    }
    if(m_EventPropertiesIsSet)
    {
        val[U("eventProperties")] = ModelBase::toJson(m_EventProperties);
    }
    val[U("eventTimestamp")] = ModelBase::toJson(m_EventTimestamp);
    val[U("requestType")] = ModelBase::toJson(m_RequestType);
    val[U("sendTimestamp")] = ModelBase::toJson(m_SendTimestamp);
    val[U("userId")] = ModelBase::toJson(m_UserId);
    

    return val;
}

void DataCollectorNewUserRequest::fromJson(web::json::value& val)
{
    if(val.has_field(U("deviceId")))
    {
        setDeviceId(ModelBase::stringFromJson(val[U("deviceId")]));
        
    }
    if(val.has_field(U("eventProperties")))
    {
        if(!val[U("eventProperties")].is_null())
        {
            std::shared_ptr<Object> newItem(nullptr);
            newItem->fromJson(val[U("eventProperties")]);
            setEventProperties( newItem );
        }
        
    }
    setEventTimestamp(ModelBase::int64_tFromJson(val[U("eventTimestamp")]));
    setRequestType(ModelBase::stringFromJson(val[U("requestType")]));
    setSendTimestamp(ModelBase::int64_tFromJson(val[U("sendTimestamp")]));
    setUserId(ModelBase::stringFromJson(val[U("userId")]));
    
}

void DataCollectorNewUserRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_DeviceIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("deviceId"), m_DeviceId));
        
    }
    if(m_EventPropertiesIsSet)
    {
        if (m_EventProperties.get())
        {
            m_EventProperties->toMultipart(multipart, U("eventProperties."));
        }
        
    }
    multipart->add(ModelBase::toHttpContent(namePrefix + U("eventTimestamp"), m_EventTimestamp));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("requestType"), m_RequestType));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("sendTimestamp"), m_SendTimestamp));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("userId"), m_UserId));
    
}

void DataCollectorNewUserRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("deviceId")))
    {
        setDeviceId(ModelBase::stringFromHttpContent(multipart->getContent(U("deviceId"))));
        
    }
    if(multipart->hasContent(U("eventProperties")))
    {
        if(multipart->hasContent(U("eventProperties")))
        {
            std::shared_ptr<Object> newItem(nullptr);
            newItem->fromMultiPart(multipart, U("eventProperties."));
            setEventProperties( newItem );
        }
        
    }
    setEventTimestamp(ModelBase::int64_tFromHttpContent(multipart->getContent(U("eventTimestamp"))));
    setRequestType(ModelBase::stringFromHttpContent(multipart->getContent(U("requestType"))));
    setSendTimestamp(ModelBase::int64_tFromHttpContent(multipart->getContent(U("sendTimestamp"))));
    setUserId(ModelBase::stringFromHttpContent(multipart->getContent(U("userId"))));
    
}


utility::string_t DataCollectorNewUserRequest::getDeviceId() const
{
    return m_DeviceId;
}
void DataCollectorNewUserRequest::setDeviceId(utility::string_t value)
{
    m_DeviceId = value;
    m_DeviceIdIsSet = true;
}
bool DataCollectorNewUserRequest::deviceIdIsSet() const
{
    return m_DeviceIdIsSet;
}
void DataCollectorNewUserRequest::unsetDeviceId()
{
    m_DeviceIdIsSet = false;
}
std::shared_ptr<Object> DataCollectorNewUserRequest::getEventProperties() const
{
    return m_EventProperties;
}
void DataCollectorNewUserRequest::setEventProperties(std::shared_ptr<Object> value)
{
    m_EventProperties = value;
    m_EventPropertiesIsSet = true;
}
bool DataCollectorNewUserRequest::eventPropertiesIsSet() const
{
    return m_EventPropertiesIsSet;
}
void DataCollectorNewUserRequest::unsetEventProperties()
{
    m_EventPropertiesIsSet = false;
}
int64_t DataCollectorNewUserRequest::getEventTimestamp() const
{
    return m_EventTimestamp;
}
void DataCollectorNewUserRequest::setEventTimestamp(int64_t value)
{
    m_EventTimestamp = value;
    
}
utility::string_t DataCollectorNewUserRequest::getRequestType() const
{
    return m_RequestType;
}
void DataCollectorNewUserRequest::setRequestType(utility::string_t value)
{
    m_RequestType = value;
    
}
int64_t DataCollectorNewUserRequest::getSendTimestamp() const
{
    return m_SendTimestamp;
}
void DataCollectorNewUserRequest::setSendTimestamp(int64_t value)
{
    m_SendTimestamp = value;
    
}
utility::string_t DataCollectorNewUserRequest::getUserId() const
{
    return m_UserId;
}
void DataCollectorNewUserRequest::setUserId(utility::string_t value)
{
    m_UserId = value;
    
}

}
}
}
}

